# Generated by Django 4.0.4 on 2022-05-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
