# Generated by Django 4.0.4 on 2022-05-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemcategory')),
                ('item', models.ManyToManyField(to='items.item')),
            ],
        ),
    ]
