# Generated by Django 4.0.4 on 2022-05-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_categoryitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCategory',
            new_name='Categories',
        ),
        migrations.RemoveField(
            model_name='categoryitems',
            name='item',
        ),
        migrations.AddField(
            model_name='categoryitems',
            name='item',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
