# Generated by Django 4.0.4 on 2022-05-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_rename_itemcategory_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
