# Generated by Django 4.0.4 on 2022-05-13 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userimage_userid_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0013_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoffer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemoffer',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
