# Generated by Django 4.0.4 on 2022-05-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_itemoffer_owner_alter_itemoffer_buyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemOffer',
        ),
    ]
