# Generated by Django 4.0.4 on 2022-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_start', models.DateTimeField()),
                ('logo', models.CharField(blank=True, max_length=9999)),
            ],
        ),
    ]
