# Generated by Django 4.0.4 on 2022-05-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buyer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
