# Generated by Django 4.0.4 on 2022-05-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_user_username_remove_user_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='name',
        ),
    ]
