# Generated by Django 4.0.4 on 2022-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_paymentdetails_cardnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='cvv',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
