# Generated by Django 4.0.4 on 2022-05-13 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_alter_paymentdetails_cvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('userBeingRated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_being_rated', to=settings.AUTH_USER_MODEL)),
                ('userGivingRating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_giving_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
