# Generated by Django 4.0.4 on 2022-05-13 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='Order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_rating', to='orders.orderdetails'),
            preserve_default=False,
        ),
    ]
