# Generated by Django 4.0.4 on 2022-05-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rating_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Order',
            new_name='order',
        ),
    ]
